# Generated by Django 3.0.2 on 2020-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200723_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, default='testimony/avatar.jpg', null=True, upload_to='testimony/')),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=True)),
                ('role', models.CharField(blank=True, default='Developer', max_length=50, null=True)),
            ],
        ),
    ]
