# Generated by Django 3.0.2 on 2020-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeimage',
            name='download_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
