# Generated by Django 3.0.2 on 2020-08-03 07:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_shapeimage_download_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShapeDeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('reason', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ShapeImage')),
            ],
        ),
    ]
